# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d23808f8a4e3c2637a883d58985853d0379dd0f1785d0ba7db19361c44ebafcb241297acf602e683f89d49983a386819e62b507a33589688e1aa729c483007

test:
  secret_key_base: ce3e56d72057ec74f342a551392dab16525471d39f680f656f59d7a69c0aa28138a8c03976474b096597c323a429600c2a34a83be55a530469174f08523fc182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
